<?xml version="1.0"?>
<package format="2">

  <name>tandem</name>
  <version>0.0.0</version>
  <description>ROS package for Girona500 visual inspection and final approach control</description>
  <maintainer email="nicolas.lopez@uib.cat">Nicolas Lopez-Martorell</maintainer>

  <license>BSD-4-Clause</license>


  <author email="nicolas.lopez@uib.cat">Nicolas Lopez-Martorell</author>


  <!-- Build tool -->
  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>dynamic_reconfigure</depend>
  <depend>cola2_msgs</depend>
  <depend>net_hole_detector</depend>
</package>
